# Generated by Django 4.1.5 on 2023-02-13 05:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Treads',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64)),
                ('content', models.TextField()),
                ('created_time', models.DateTimeField(default=datetime.datetime(2023, 2, 13, 8, 18, 40, 870029))),
            ],
        ),
    ]
